export const SET_CURRENT_TODO = "SET_CURRENT_TODO";
export const GET_CURRENT_TODO = "GET_CURRENT_TODO";

export const SET_TODO_TO_ADD = "SET_TODO_TO_ADD";
export const GET_TODO_TO_ADD = "GET_TODO_TO_ADD";

export const FIND_BY_TITLE = "FIND_BY_TITLE";
export const FIND_BY_TITLE_SUCCESSFUL = "FIND_BY_TITLE_SUCCESSFUL";

export const SET_SEARCH_TITLE = "SET_SEARCH_TITLE";
export const GET_SEARCH_TITLE = "GET_SEARCH_TITLE";

export const SET_MESSAGE = "SET_MESSAGE";
export const GET_MESSAGE = "GET_MESSAGE";

export const SET_SUBMITTED = "SET_SUBMITTED";
export const GET_SUBMITTED = "GET_SUBMITTED";

export const SET_CURRENT_INDEX = "SET_CURRENT_INDEX";
export const GET_CURRENT_INDEX = "GET_CURRENT_INDEX";

export const GET_TODOS = "GET_TODOS";
export const GET_TODOS_SUCCESSFUL = "GET_TODOS_SUCCESSFUL";
export const SET_TODOS = "SET_TODOS";

export const GET_TODO = "GET_TODO";

export const ADD_TODO = "ADD_TODO";
export const ADD_TODO_SUCCESSFUL = "ADD_TODO_SUCCESSFUL";

export const UPDATE_TODO = "UPDATE_TODO";
export const UPDATE_TODO_SUCCESSFUL = "UPDATE_TODO_SUCCESSFUL";

export const DELETE_TODO = "DELETE_TODO";
export const DELETE_TODO_SUCCESSFUL = "DELETE_TODO_SUCCESSFUL";

export const DELETE_TODOS = "DELETE_TODOS";
export const DELETE_TODOS_SUCCESSFUL = "DELETE_TODOS_SUCCESSFUL";

// export const DATA_LOADED = "DATA_LOADED";
export const API_ERRORED = "API_ERRORED";

export const IS_FETCHING = "IS_FETCHING";
export const IS_UPDATING = "IS_UPDATING";
export const IS_DELETING = "IS_DELETING";
export const IS_DELETING_ALL = "IS_DELETING_ALL";
export const IS_ADDING = "IS_ADDING";
export const IS_FINDING = "IS_FINDING";
