export const SET_CURRENT_CALENDAR_EVENT = "SET_CURRENT_CALENDAR_EVENT";
export const GET_CURRENT_CALENDAR_EVENT = "GET_CURRENT_CALENDAR_EVENT";

export const SET_CALENDAR_EVENT_TO_ADD = "SET_CALENDAR_EVENT_TO_ADD";
export const GET_CALENDAR_EVENT_TO_ADD = "GET_CALENDAR_EVENT_TO_ADD";

export const FIND_BY_TITLE = "FIND_BY_TITLE";
export const FIND_BY_TITLE_SUCCESSFUL = "FIND_BY_TITLE_SUCCESSFUL";

export const SET_SEARCH_TITLE = "SET_SEARCH_TITLE";
export const GET_SEARCH_TITLE = "GET_SEARCH_TITLE";

export const SET_MESSAGE = "SET_MESSAGE";
export const GET_MESSAGE = "GET_MESSAGE";

export const SET_SUBMITTED = "SET_SUBMITTED";
export const GET_SUBMITTED = "GET_SUBMITTED";

export const SET_CURRENT_INDEX = "SET_CURRENT_INDEX";
export const GET_CURRENT_INDEX = "GET_CURRENT_INDEX";

export const GET_CALENDAR_EVENTS = "GET_CALENDAR_EVENTS";
export const GET_CALENDAR_EVENTS_SUCCESSFUL = "GET_CALENDAR_EVENTS_SUCCESSFUL";
export const SET_CALENDAR_EVENTS = "SET_CALENDAR_EVENTS";

export const GET_CALENDAR_EVENT = "GET_CALENDAR_EVENT";
export const GET_CALENDAR_EVENT_SUCCESSFUL = "GET_CALENDAR_EVENT_SUCCESSFUL";

export const ADD_CALENDAR_EVENT = "ADD_CALENDAR_EVENT";
export const ADD_CALENDAR_EVENT_SUCCESSFUL = "ADD_CALENDAR_EVENT_SUCCESSFUL";

export const UPDATE_CALENDAR_EVENT = "UPDATE_CALENDAR_EVENT";
export const UPDATE_CALENDAR_EVENT_SUCCESSFUL = "UPDATE_CALENDAR_EVENT_SUCCESSFUL";

export const DELETE_CALENDAR_EVENT = "DELETE_CALENDAR_EVENT";
export const DELETE_CALENDAR_EVENT_SUCCESSFUL = "DELETE_CALENDAR_EVENT_SUCCESSFUL";

export const DELETE_CALENDAR_EVENTS = "DELETE_CALENDAR_EVENTS";
export const DELETE_CALENDAR_EVENTS_SUCCESSFUL = "DELETE_CALENDAR_EVENTS_SUCCESSFUL";

// export const DATA_LOADED = "DATA_LOADED";
export const API_ERRORED = "API_ERRORED";

export const IS_FETCHING = "IS_FETCHING";
export const IS_UPDATING = "IS_UPDATING";
export const IS_DELETING = "IS_DELETING";
export const IS_DELETING_ALL = "IS_DELETING_ALL";
export const IS_ADDING = "IS_ADDING";
export const IS_FINDING = "IS_FINDING";